apiVersion: v1
kind: Pod
metadata: 
  name: my-app
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-vol
      mountPath: /data
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
  volumes:
  - name: nginx-vol
    emptyDir: {}
