apiVersion: v1
kind: Pod
metadata: 
  name: my-app
  namespace: web
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "200m"
          memory: "1Gi"
