apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: nginx-rc-pod
  template:
    metadata:
      labels:
        app: nginx-rc-pod
    spec:
      containers:
      - name: nginx
        image: nginx 
        ports:
        - containerPort: 80
          protocol: TCP
