apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv
  labels:
    app: my-pv
spec:
  resources:
    requests:
     storage: "500Mi"
  storageClassName: hostpath
  selector:
    matchLabels:
      app: my-pv
  accessModes:
  - ReadWriteOnce
