apiVersion: v1
kind: Pod
metadata:
  name: ready
  labels:
    app: ready
spec:
  containers:
  - name: ready
    image: ubuntu
    command: ['sh', '-c', 'if [ -f "work-dir/ready" ]; then sleep infinity; else exit 1; fi ']
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  initContainers:
  - name: install
    image: busybox:1.28
    command: ['sh', '-c', 'touch /work-dir/ready;']
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"
  volumes:
  - name: workdir
    emptyDir: {}
