apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication
  labels:
    app: k8-services
spec:
  replicas: 3
  selector:
    app: k8-service 
  template:
    metadata:
      labels:
        app: k8-service
      name: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1 
kind: Service  
metadata: 
  name: my-service
spec:
  type: NodePort
  selector: 
    app: k8-service
  ports:
  - name: my-app
    port: 80
    targetPort: 80
    protocol: TCP
