apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    pod: ubuntu-pod
spec:
  nodeSelector:
    worker: node1
  containers:
  - image: ubuntu
    name: ubuntu
    stdin: true
    tty: true 

