apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector:
    run: web-deploy
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-deploy
  template:
    metadata:
      labels:
        run: web-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        
        kubectl create deployment --dry-run web-deploy --image=nginx -o yaml > web-deploy.yaml
        vim web-deploy.yaml
        kubectl create -f web-deploy.yaml
        kubectl get deployments
        kubectl get pods
        kubectl get services
        kubectl run -it --generator=run-pod/v1 busybox --image=busybox:1.28 (Ctrl+p+q - not to crush container)
        kubectl get pods
        kubectl exec busybox -- nslookup web-svc > /tasks/ORMNZZON07/service.txt
        cat /tasks/ORMNZZON07/service.txt
        kubectl get pods -o wide
        kubectl exec busybox -- nslookup 10-38-0-6.default.pod.cluster.local > /tasks/ORMNZZON07/pod.txt


this one works:
nslookup 10-38-0-6.default.pod.cluster.local
Server:  10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
Name:   10-38-0-6.default.pod.cluster.local
Address 1: 10.38.0.6 10-38-0-6.web-deploy.default.svc.cluster.local
